import './common/alert/Alert';
import './common/color-picker/ColorPicker';
import './common/dropdown-menu/DropdownMenu';
import './common/expandable/Expandable';
import './common/file-dropzone/FileDropzone';
import './common/inline-menu/InlineMenu';
import './common/radio-group/RadioGroup';
import './common/radio-group/RadioItem';
import './common/rotary-knob/RotaryKnob';
import './common/slider/Slider';
import './common/switch/Switch';
import './common/tooltip/Tooltip';

import './components/aes-encryption/AesEncryption';
import './components/ascii-encoder/AsciiEncoder';
import './components/base64-encoder/Base64Encoder';
import './components/color-convertor/ColorConvertor';
import './components/color-mixer/ColorMixer';
import './components/color-palette/ColorPalette';
import './components/contrast-checker/ContrastChecker';
import './components/cubic-bezier/CubicBezier';
import './components/data-format-convertor/DataFormatConvertor';
import './components/datetime-convertor/DatetimeConvertor';
import './components/diff-checker/DiffChecker';
import './components/gradient-maker/GradientMaker';
import './components/html-xml-editor/HtmlXmlEditor';
import './components/text-editor/TextEditor';
import './components/text-editor/TextEditorEditor';
import './components/json-editor/JsonEditor';
import './components/jwt-inspector/JwtInspector';
import './components/password-generator/PasswordGenerator';
import './components/qr-code-generator/QrCodeGenerator';
import './components/token-generator/TokenGenerator';
import './components/rsa-encryption/RsaEncryption';
import './components/rsa-key-generator/RsaKeyGenerator';
import './components/sha-hashing/ShaHashing';
import './components/signature-verifier/SignatureVerifier';
import './components/unicode-inspector/UnicodeInspector';
import './components/unix-path-convertor/UnixPathConvertor';
import './components/url-encoder/UrlEncoder';
import './components/url-parser/UrlParser';
import './components/uuid-generator/UuidGenerator';
import './components/yaml-editor/YamlEditor';

window.addEventListener('load', () => {
    console.log('Tool components loaded');
});